# Cloudflare Pages Configuration
name = "nsy-tax-freelancer"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"

[assets]
directory = "./out"

[env.production]
NODE_VERSION = "18"

[env.preview]
NODE_VERSION = "18"
