# Cloudflare Pages Configuration
name = "nsy-tax-freelancer"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"

[build.upload]
format = "directory"
dir = "out"

# Environment variables for build
[env.production]
NODE_VERSION = "18"

[env.preview]
NODE_VERSION = "18"