# Cloudflare Pages Configuration
name = "nsy-tax-freelancer"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
cwd = "."

[build.upload]
format = "directory"
dir = ".next"

# Environment variables
[env.production.vars]
NODE_ENV = "production"

[env.preview.vars]
NODE_ENV = "development"